export const siteUrl = 'https://mitchellnchistory.org'

export const sitemapRoutes = [
  '/',
  '/about/',
  '/museum/',
  '/membership/',
  '/apple-butter-festival/',
  '/contact/',
  '/articles/',
  '/scholarship/',
  '/scan-days/',
  '/penland-cemetery/',
  '/overmountain-men/',
  '/corona-times/',
  '/newsletters/',
  '/history-bee/',
  '/red-wilson/',
  '/about-mitchell-county/',
  '/videos/',
  '/resources/',
  '/cookie-policy/',
  '/donation-policy/',
  '/free-for-charity-donation-policy/',
  '/privacy-policy/',
  '/security-acknowledgements/',
  '/terms-of-service/',
  '/vulnerability-disclosure-policy/',
] as const
